In [5]:
import numpy as np
array2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print("Vector:", array2)
a = array2.reshape(3,5)
print("Two dimensional array: ", a)

print("Shape:", a.shape)
print("Dimension:", a.ndim)
print("Data Type:", a.dtype.name)
print("Size: ", a.size)
print("Type: ", type(a))

Vector: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Two dimensional array:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Shape: (3, 5)
Dimension: 2
Data Type: int64
Size:  15
Type:  <class 'numpy.ndarray'>


In [7]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x+y)
print(x-y)
print(x**2)

[5 7 9]
[-3 -3 -3]
[1 4 9]


In [8]:
a = np.array([1,2,3])
d = a.copy
print(d)
b=a
c=a
b[0] = 5
print(a,b,c)

<built-in method copy of numpy.ndarray object at 0x7fccc8038870>
[5 2 3] [5 2 3] [5 2 3]


In [9]:
a = np.array([1,2,3,4,5,6,7])
print(a[0])
print(a[0:4])

1
[1 2 3 4]


In [ ]:
reverse_array = a[::-1]
print(reverse_array)

In [ ]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)
print(b[1,1])
print(b[:,1])
print(b[1,:])
print(b[1,1:4])
#print(b[])
